"""
ASGI config for moviesite project.

This module exposes the ASGI callable as a module-level variable named
``application``.

It follows the default template generated by ``django-admin startproject``.

See https://docs.djangoproject.com/en/5.0/howto/deployment/asgi/ for
more information on ASGI deployments.
"""

import os

from django.core.asgi import get_asgi_application  # type: ignore

# Set the default settings module for the 'asgi' program.
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "moviesite.settings")

application = get_asgi_application()