"""
WSGI config for moviesite project.

This module exposes the WSGI callable as a module-level variable named
``application``.

It follows the default template generated by ``django-admin startproject``.

See https://docs.djangoproject.com/en/5.0/howto/deployment/wsgi/ for
more information on WSGI deployments.
"""

import os

from django.core.wsgi import get_wsgi_application  # type: ignore

# Set the default settings module for the 'wsgi' program.
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "moviesite.settings")

application = get_wsgi_application()