# Generated by Django 5.2.7 on 2025-10-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la película', max_length=200)),
                ('director', models.CharField(help_text='Director de la película', max_length=100)),
                ('rating', models.CharField(help_text='Clasificación (por ejemplo, PG-13)', max_length=10)),
                ('release_year', models.PositiveIntegerField(help_text='Año de estreno')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('genre', models.CharField(choices=[('COM', 'Comedia'), ('ROM', 'Romance'), ('ADV', 'Aventura'), ('HOR', 'Terror'), ('ACC', 'Acción'), ('DRA', 'Drama'), ('SCI', 'Ciencia ficción'), ('OTH', 'Otro')], default='OTH', help_text='Género de la película', max_length=3)),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['title'],
            },
        ),
    ]
