#!/usr/bin/env python
"""
This file is an entry‑point for a Django project.  It mirrors the default
`manage.py` generated by ``django-admin startproject`` and allows you to run
administrative commands such as starting the development server, running
migrations or creating new apps.

You can invoke this script with various sub‑commands, for example::

    python manage.py runserver
    python manage.py makemigrations
    python manage.py migrate

The script sets the default settings module for the project and then
delegates to Django's ``execute_from_command_line()`` utility.  See the
Django documentation for more details.
"""

import os
import sys


def main() -> None:
    """Run administrative tasks."""
    # Configure the settings module.  Without this environment variable Django
    # doesn't know which settings to use.  Replace ``moviesite.settings`` with
    # the dotted path to your own settings module if you change the project
    # structure.
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "moviesite.settings")
    try:
        # Import here so that an informative error is raised if Django is not
        # installed.  The ImportError message will instruct the user to
        # install Django or activate a virtual environment.
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    # Forward command‑line arguments to Django's management utility.
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()